### PR TITLE
Added Mailing button and redirected it to contactasetalias@gmail.com

### PR DESCRIPTION
**Pull request by Manas-kashyap**
Working button is added at the main screen . 
photo_2017-10-13_22-12-24
photo_2017-10-13_22-12-32

### CODE REVIEW

**Comment by thisisayush** [comment]
We decided material design. Please update the mail button according to material design guidelines. :)

**Comment by Manas-kashyap** [comment]
What is material design

**Comment by Manas-kashyap** [comment]
And how should i make it

**Comment by AniVerma17** [comment]
Goto https://material.io for Material Desigh guidelines.

**Comment by Manas-kashyap** [comment]
okay

**Comment by Manas-kashyap** [comment]
But can you please tell , what changes i have to do ,I am not getting what do you really want , how should i put the mail button.

**Comment by thisisayush** [comment]
This Branch has conflicts and must be resolved before merging.
@Manas-kashyap

**Pull request closed without merging**
